#!/bin/sh
 
src_path=/directory/path/to/monitor
 
inotifywait --format '%:e %w%f' -e modify,delete,create \
        --exclude '^.+(jpe?g|gif|ico|png|svg|pdf|pptx?|swpx|swp)$' \
        -m -r "$src_path" | \
        while read watched_filename EVENT_NAMES; do
                case "$watched_filename" in
                        MODIFY)
                                echo "$EVENT_NAMES has been modified"
                                ;;
                        CREATE)
                                echo "$EVENT_NAMES has been created"
                                ;;
                        DELETE)
                                echo "$EVENT_NAMES has been deleted"
                                ;;
                        *) echo "Unknown event, exiting";break
                esac
        done
